# Generated by Django 5.0.2 on 2024-02-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berries', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Ягоды',
                'verbose_name_plural': 'Ягоды',
                'ordering': ('berries',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Декор',
                'verbose_name_plural': 'Декор',
                'ordering': ('decor',),
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Надпись',
                'verbose_name_plural': 'Надпись',
                'ordering': ('inscription',),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_levels', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Уровни тортиков',
                'verbose_name_plural': 'Уровни тортиков',
                'ordering': ('number_of_levels',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Форма тортиков',
                'verbose_name_plural': 'Формы тортиков',
                'ordering': ('shape',),
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Топпинг',
                'verbose_name_plural': 'Топпинги',
                'ordering': ('topping',),
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.berries')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cake', to='polls.client')),
                ('decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.decor')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.inscription')),
                ('number_of_levels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.level')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.price')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.shape')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.topping')),
            ],
            options={
                'verbose_name': 'Тортик',
                'verbose_name_plural': 'Тортики',
                'ordering': ('number_of_levels',),
            },
        ),
    ]
