# Generated by Django 5.0.2 on 2024-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_cake_berries_alter_cake_decor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='adress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cake',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='datetime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
