# Generated by Django 5.0.2 on 2024-02-17 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_berries_price_decor_price_inscription_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.price'),
        ),
    ]
