# Generated by Django 5.0.2 on 2024-02-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_decor_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='price',
        ),
        migrations.RemoveField(
            model_name='berries',
            name='price',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='price',
        ),
        migrations.RemoveField(
            model_name='level',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shape',
            name='price',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='price',
        ),
        migrations.AddField(
            model_name='berries',
            name='price',
            field=models.ManyToManyField(default=0, to='polls.price'),
        ),
        migrations.AddField(
            model_name='decor',
            name='price',
            field=models.ManyToManyField(default=0, to='polls.price'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='price',
            field=models.ManyToManyField(default=0, to='polls.price'),
        ),
        migrations.AddField(
            model_name='level',
            name='price',
            field=models.ManyToManyField(default=0, to='polls.price'),
        ),
        migrations.AddField(
            model_name='shape',
            name='price',
            field=models.ManyToManyField(default=0, to='polls.price'),
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.ManyToManyField(default=0, to='polls.price'),
        ),
    ]
