# Generated by Django 5.0.2 on 2024-02-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_berries_price_remove_decor_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='berries',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.price'),
        ),
        migrations.AddField(
            model_name='decor',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.price'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.price'),
        ),
        migrations.AddField(
            model_name='level',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.price'),
        ),
        migrations.AddField(
            model_name='shape',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.price'),
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.price'),
        ),
    ]
