# Generated by Django 5.0.2 on 2024-02-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_price_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('price',), 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
    ]
